### ISSUE TITLE
ImportError: The _imagingft C module is not installed

### ISSUE THREAD

**Issue by leollon** [leollon/mysite#7]
在 `python:3.7-alpine` docker 镜像上使用 `pillow` 生成验证码引发 500 Internal Server Error.

```
[ERROR] [2019-11-20 03:28:35,426] [log] pid:31 [Internal Server Error: /refresh/captcha/]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/mysite/apps/captcha/views.py", line 18, in get
    captcha.generate_captcha()
  File "/mysite/apps/captcha/captcha.py", line 159, in generate_captcha
    text = self.create_text()  # 将会被放到缓存中
  File "/mysite/apps/captcha/captcha.py", line 119, in create_text
    font = ImageFont.truetype(self._font_type, self._font_size)
  File "/usr/local/lib/python3.7/site-packages/PIL/ImageFont.py", line 640, in truetype
    return freetype(font)
  File "/usr/local/lib/python3.7/site-packages/PIL/ImageFont.py", line 637, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "/usr/local/lib/python3.7/site-packages/PIL/ImageFont.py", line 161, in __init__
    if core.HAVE_RAQM:
  File "/usr/local/lib/python3.7/site-packages/PIL/ImageFont.py", line 41, in __getattr__
    raise ImportError("The _imagingft C module is not installed")
ImportError: The _imagingft C module is not installed
```

**Comment by leollon** [comment]
Needed to add library as follows:

```bash
apk add --no-cache freetype-dev \
        lcms2-dev openjpeg-dev harfbuzz-dev \
        fribidi-dev 
```

Referer to [this](https://github.com/python-pillow/docker-images/blob/master/alpine/Dockerfile#L21).
